version: "3"
services:
 rabbitmq:
    hostname: 'rabbit-mq'
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-vol:/var/lib/rabbitmq
volumes:
  rabbitmq-vol:
      driver: local
      